# Generated by Django 3.1.3 on 2023-02-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230212_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
