# Generated by Django 3.1.3 on 2023-02-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_file', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
