# Generated by Django 3.1.3 on 2023-02-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attendancefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceFile',
        ),
    ]
