# Generated by Django 3.1.3 on 2023-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_attendancefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastface',
            name='last_face',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hostelname',
            field=models.CharField(choices=[('None', 'None'), ('cvr', 'cvr'), ('asr', 'asr'), ('vvk', 'vvk'), ('vsr', 'vsr'), ('sac', 'sac')], default='employee', max_length=20, null=True),
        ),
    ]
