# Generated by Django 3.1.3 on 2023-03-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230304_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hostel_type',
            field=models.CharField(choices=[('None', 'None'), ('AC', 'AC'), ('Non AC', 'Non AC')], max_length=20, null=True),
        ),
    ]
