# Generated by Django 3.1.3 on 2023-03-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_hostel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hostel_type',
            new_name='hosteltype',
        ),
    ]
