# Generated by Django 3.1.3 on 2023-03-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parentphone',
            field=models.BigIntegerField(null=True),
        ),
    ]
