# Generated by Django 3.1.3 on 2023-03-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_parentphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hostelname',
            field=models.CharField(choices=[('None', 'None'), ('cvr', 'cvr'), ('asr', 'asr'), ('vvk', 'vvk'), ('vsr', 'vsr'), ('sac', 'sac'), ('dvr', 'dvr')], default='employee', max_length=20, null=True),
        ),
    ]
